title: Pexip App Development
description: Develop cross platform apps for use against Pexip API's
author:
  name: Ian Mortimer
  email: ian@pexip.com
url: https://pexip.github.io/pexkit-sdk/
theme: jekyll-theme-cayman
markdown: kramdown